---
- id: hadolint-docker
  name: Lint Dockerfiles
  description: Runs hadolint Docker image to lint Dockerfiles
  language: docker_image
  types: ["dockerfile"]
  entry: ghcr.io/hadolint/hadolint:v2.14.0@sha256:27086352fd5e1907ea2b934eb1023f217c5ae087992eb59fde121dce9c9ff21e hadolint
- id: hadolint
  name: Lint Dockerfiles
  description: Runs hadolint to lint Dockerfiles
  language: system
  types: ["dockerfile"]
  entry: hadolint
