name: hadolint
version: "2.7.0"
synopsis: Dockerfile Linter JavaScript API
description: A smarter Dockerfile linter that helps you build best practice Docker images.
category: Development
author: Lukas Martinelli
maintainer: me@lukasmartinelli.ch
copyright: Lukas Martinelli
license: GPL-3
homepage: https://github.com/hadolint/hadolint
git: git@github.com:hadolint/hadolint.git
extra-source-files: README.md
flags:
  static:
    description: Use static linking for the hadolint executable
    default: true
    manual: true
ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -optP-Wno-nonportable-include-path
  - -flate-dmd-anal
dependencies:
  - base >=4.8 && <5
  - megaparsec >= 9.0.0
  - language-docker >=10.1.0 && <11
default-extensions:
  - OverloadedStrings
  - NamedFieldPuns
  - DeriveGeneric
  - DeriveAnyClass
  - RecordWildCards
  - StrictData
  - ScopedTypeVariables
  - PatternSynonyms
library:
  source-dirs: src
  generated-other-modules:
    - Paths_hadolint
  dependencies:
    - &ShellCheck ShellCheck >=0.7.1
    - &bytestring bytestring >=0.10
    - &split split >=0.2
    - Cabal
    - HsYAML
    - aeson
    - bytestring
    - colourista
    - containers
    - cryptonite
    - deepseq == 1.4.4.*
    - directory >= 1.3.0
    - filepath
    - ilist
    - mtl
    - network-uri
    - parsec >= 3.1.14
    - parallel
    - semver
    - spdx
    - text
    - time
    - timerep >= 2.0
    - void
    - foldl
    - email-validate
executables:
  hadolint:
    main: Main.hs
    source-dirs: app
    dependencies:
      - hadolint
      - optparse-applicative >= 0.14.0
      - gitrev >=1.3.1
      - text
      - containers
    ghc-options: -O2 -threaded -rtsopts "-with-rtsopts=-N5 -A4m"
    default-extensions:
      - TemplateHaskell
    when:
      # OS X does not support static build https://developer.apple.com/library/content/qa/qa1118
      - condition: "flag(static) && !(os(osx))"
        ld-options:
          - -static
          - -pthread
tests:
  hadolint-unit-tests:
    main: Spec.hs
    source-dirs: test
    default-extensions:
      - ImplicitParams
      - OverloadedLists
    dependencies:
      - *bytestring
      - *split
      - *ShellCheck
      - aeson
      - text
      - HUnit >=1.2
      - hspec
      - hadolint
      - HsYAML
      - foldl
      - containers
