name: hadolint
version: "2.8.0"
synopsis: Dockerfile Linter JavaScript API
description:
  A smarter Dockerfile linter that helps you build best practice Docker images.
category: Development
author: Lukas Martinelli
maintainer: me@lukasmartinelli.ch
copyright: Lukas Martinelli
license: GPL-3
homepage: https://github.com/hadolint/hadolint
git: git@github.com:hadolint/hadolint.git
extra-source-files: README.md
flags:
  static:
    description: Use static linking for the hadolint executable
    default: true
    manual: true
ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -optP-Wno-nonportable-include-path
  - -flate-dmd-anal
dependencies:
  - base >=4.8 && <5
  - containers
  - data-default
  - language-docker >=10.4.1 && <11
  - megaparsec >= 9.0.0
  - optparse-applicative >= 0.14.0
  - text
default-extensions:
  - DeriveAnyClass
  - DeriveGeneric
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RecordWildCards
  - ScopedTypeVariables
  - StrictData
  - TemplateHaskell
  - TupleSections

library:
  source-dirs: src
  generated-other-modules:
    - Paths_hadolint
  dependencies:
    - &Prettyprint prettyprinter >= 1.7.0
    - &ShellCheck ShellCheck >=0.8.0
    - &bytestring bytestring >=0.10
    - &split split >=0.2
    - Cabal
    - HsYAML
    - aeson
    - bytestring
    - colourista
    - cryptonite
    - deepseq == 1.4.4.*
    - directory >= 1.3.0
    - email-validate
    - filepath
    - foldl
    - gitrev >=1.3.1
    - ilist
    - mtl
    - network-uri
    - parallel
    - parsec >= 3.1.14
    - semver
    - spdx
    - time
    - timerep >= 2.0
    - void

executables:
  hadolint:
    main: Main.hs
    source-dirs: app
    dependencies:
      - *Prettyprint
      - hadolint
    ghc-options: -O2 -threaded -rtsopts "-with-rtsopts=-N5 -A4m"
    when:
      # OS X does not support static build
      # https://developer.apple.com/library/content/qa/qa1118
      - condition: "flag(static) && !(os(osx))"
        ld-options:
          - -static
          - -pthread

tests:
  hadolint-unit-tests:
    main: Spec.hs
    source-dirs: test
    default-extensions:
      - ImplicitParams
      - OverloadedLists
    dependencies:
      - *ShellCheck
      - *bytestring
      - *split
      - HUnit >=1.2
      - HsYAML
      - aeson
      - foldl
      - hadolint
      - hspec >= 2.8.3
      - silently
