#!/bin/bash

echo "=> Building container"
docker build \
  --tag "$IMAGE_NAME" \
  --file Dockerfile ..

docker build \
  --tag "${IMAGE_NAME}-debian" \
  --file Dockerfile .. \
  --target debian-distro
