#!/bin/bash

echo "=> Building container"
docker build \
  --tag "$IMAGE_NAME" \
  --file Dockerfile ..

docker build \
  --tag "$DOCKER_REPO":"$CACHE_TAG"-debian \
  --file Dockerfile .. \
  --target debian-distro
