name: Build With Nix
on:
  pull_request:

jobs:
  linux-static:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= kronor.cachix.org-1:AcZQBZxsK0SSlBoWmD0dNxfmtSoXueMcDBAhxzGb0MU=
          substituters = https://hydra.iohk.io https://cache.nixos.org/ https://iohk.cachix.org

    - uses: cachix/cachix-action@v10
      with:
        name: hadolint
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build Linux Static
      run: nix-build release.nix -A linux-static -j3

    - name: Verify static
      run: ldd result/bin/hadolint
