# Release workflow. Triggered by pushing a new version number in the Cabal file to the master
# branch.

name: Release

permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  autotag:
    name: Automatically Create Git Tag from Cabal file
    runs-on: ubuntu-latest
    outputs:
      created: ${{ steps.autotag.outputs.created }}
      name: ${{ steps.autotag.outputs.name }}

    steps:

      - name: Check Out
        uses: actions/checkout@v7

      - name: Create git tag from Cabal file
        uses: sol/haskell-autotag@v1
        id: autotag

      - name: Write autotag output to GitHub state
        run: |
          echo "created=${{ steps.autotag.outputs.created }}" >> "$GITHUB_OUTPUT"
          echo "name=${{ steps.autotag.outputs.name }}" >> "$GITHUB_OUTPUT"


  hackage-release:
    name: Create Hackage Release Candidate
    runs-on: ubuntu-latest
    needs:
      - autotag
    if: needs.autotag.outputs.created

    steps:

      - name: Check Out
        uses: actions/checkout@v7

      - name: Setup Haskell
        if: steps.autotag.outputs.created
        uses: haskell-actions/setup@v2
        with:
          ghc-version: 9.10.2

      - name: Build documentation and source archive
        if: steps.autotag.outputs.created
        run: |
          cabal check
          cabal sdist
          cabal haddock --haddock-for-hackage

      - name: Upload Candidate to Hackage
        if: steps.autotag.outputs.created
        uses: haskell-actions/hackage-publish@v1.1
        with:
          hackageToken: ${{ secrets.HACKAGE_AUTH_TOKEN }}
          packagesPath: ${{ github.workspace }}/dist-newstyle/sdist
          docsPath: ${{ github.workspace }}/dist-newstyle
          publish: false


  build-linux:
    name: Create Release for Linux (static)
    needs:
      - autotag
    if: needs.autotag.outputs.created
    runs-on: ${{ matrix.os }}
    container:
      image: alpine:3.24
      volumes:
        - /:/host
        - /opt:/opt:rw,rshared
        - /opt:/__e/node24:ro,rshared
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-amd64
            ghcup: https://downloads.haskell.org/~ghcup/x86_64-linux-ghcup
            ghc: 9.10.2
          - os: ubuntu-24.04-arm
            target: linux-arm64
            ghcup: https://downloads.haskell.org/~ghcup/aarch64-linux-ghcup
            ghc: 9.10.2

    steps:

      - name: Workaround to make checkout work on Alpine arm64
        run: |
          sed -i "/^ID=/s/alpine/NotpineForGHA/" /etc/os-release
          apk add nodejs --update-cache
          mkdir /opt/bin
          ln -sf /usr/bin/node /opt/bin/node

      - name: Install system dependencies
        run: |
          apk add --no-cache \
            curl gcc g++ ncurses-dev libffi-dev make xz gzip tar perl git bash \
            sudo binutils-gold zlib zlib-dev zlib-static gmp gmp-dev \
            gmp-static ncurses-static libc-dev libffi-dev musl-dev

      - name: Install ghcup
        run: |
          curl \
            --proto '=https' --tlsv1.2 -sSf ${{ matrix.ghcup }} > /usr/bin/ghcup
          chmod +x /usr/bin/ghcup
          echo "$HOME/.ghcup/bin" $GITHUB_PATH
        shell: bash

      - name: Install GHC and cabal
        run: |
          ghcup install ghc   --force -i /usr/local ${{ matrix.ghc }}
          ghcup install cabal --force -i /usr/local/bin
        shell: bash

      - uses: actions/checkout@v7

      - name: Update cabal cache
        run: cabal update
        shell: bash

      - name: create ~/.local/bin
        run: mkdir -p "$HOME/.local/bin"
        shell: bash

      - run: echo "HOME=$HOME" >> $GITHUB_ENV
        shell: bash

      - name: Freeze
        run: cabal freeze

      - name: Cache store
        uses: actions/cache@v6
        with:
          path: ~/.cabal/store
          key: ${{ matrix.os }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Build
        run: |
          cabal build \
            --only-dependencies \
            --disable-shared \
            --ghc-options='-split-sections -optl-static -fPIC'
          cabal build \
            --enable-executable-static \
            --disable-executable-dynamic \
            --disable-shared \
            --ghc-options='-split-sections -optl-static -optl-pthread -fPIC'
          mv "$(cabal list-bin hadolint)" ~/.local/bin/hadolint
          strip ~/.local/bin/hadolint
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: hadolint-${{ matrix.target }}
          path: ~/.local/bin/hadolint
          retention-days: 3


  build-macos:
    name: Build MacOS Binaries
    runs-on: ${{ matrix.os }}
    needs:
      - autotag
    if: needs.autotag.outputs.created
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-15
            target: macos-x86_64
          - os: macos-15
            target: macos-arm64

    steps:
      - uses: actions/checkout@v7

      - id: setup-haskell
        name: Set up Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: 9.10.2

      - name: Freeze
        run: cabal freeze

      - name: Cache store
        uses: actions/cache@v6
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ matrix.os }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Build binaries
        run: |
          mkdir dist
          cabal install exe:hadolint \
            --install-method=copy \
            --overwrite-policy=always \
            --installdir=dist \
            --ghc-options="-fPIC"

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: hadolint-${{ matrix.target }}
          path: ./dist/hadolint
          retention-days: 3


  build-windows:
    name: Build Windows Binaries
    runs-on: ${{ matrix.os }}
    needs:
      - autotag
    if: needs.autotag.outputs.created
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: windows-x86_64

    steps:
      - uses: actions/checkout@v7

      - id: setup-haskell
        name: Set up Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: 9.10.2

      - name: Freeze
        run: cabal freeze

      - name: Cache store
        uses: actions/cache@v6
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ matrix.os }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Build binaries
        run: |
          mkdir dist
          cabal install exe:hadolint `
            --install-method=copy `
            --overwrite-policy=always `
            --installdir=dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: hadolint-${{ matrix.target }}
          path: dist\hadolint.exe
          retention-days: 3


  build-docker:
    name: Build Docker Images
    needs:
      - build-linux
      - autotag
    if: needs.autotag.outputs.created
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - amd64
          - arm64
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          name: hadolint-linux-${{matrix.target}}
          path: ${{matrix.target}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image Scratch
        uses: docker/build-push-action@v7
        with:
          context: ${{matrix.target}}
          file: docker/Dockerfile
          platforms: linux/${{matrix.target}}
          target: base
          push: true
          provenance: mode=max
          tags: |
            hadolint/hadolint:${{github.sha}}-${{matrix.target}}
            ghcr.io/hadolint/hadolint:${{github.sha}}-${{matrix.target}}

      - name: Push Docker Image Debian
        uses: docker/build-push-action@v7
        with:
          context: ${{matrix.target}}
          file: docker/Dockerfile
          platforms: linux/${{matrix.target}}
          target: debian
          push: true
          provenance: mode=max
          tags: |
            hadolint/hadolint:${{github.sha}}-debian-${{matrix.target}}
            ghcr.io/hadolint/hadolint:${{github.sha}}-debian-${{matrix.target}}

      - name: Push Docker Image Alpine
        uses: docker/build-push-action@v7
        with:
          context: ${{matrix.target}}
          file: docker/Dockerfile
          platforms: linux/${{matrix.target}}
          target: alpine
          push: true
          provenance: mode=max
          tags: |
            hadolint/hadolint:${{github.sha}}-alpine-${{matrix.target}}
            ghcr.io/hadolint/hadolint:${{github.sha}}-alpine-${{matrix.target}}


  docker-release:
    needs:
      - build-docker
      - autotag
    if: needs.autotag.outputs.created
    runs-on: ubuntu-latest
    strategy:
      matrix:
        registry:
          - hadolint/hadolint
          - ghcr.io/hadolint/hadolint
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push scratch image
        run: |
          docker pull --platform linux/amd64 ${{ matrix.registry }}:${{ github.sha }}-amd64
          docker pull --platform linux/arm64 ${{ matrix.registry }}:${{ github.sha }}-arm64
          docker buildx imagetools create \
            --tag ${{ matrix.registry }}:latest \
            ${{ matrix.registry }}:${{ needs.autotag.outputs.name }} \
            ${{ matrix.registry }}:${{github.sha}}-amd64 \
            ${{ matrix.registry }}:${{github.sha}}-arm64

      - name: Push alpine image
        run: |
          docker pull --platform linux/amd64 ${{ matrix.registry }}:${{ github.sha }}-alpine-amd64
          docker pull --platform linux/arm64 ${{ matrix.registry }}:${{ github.sha }}-alpine-arm64
            --tag ${{ matrix.registry }}:latest-alpine \
            ${{ matrix.registry }}:${{ needs.autotag.outputs.name }}-alpine \
            ${{ matrix.registry }}:${{github.sha}}-alpine-amd64 \
            ${{ matrix.registry }}:${{github.sha}}-alpine-arm64

      - name: Push debian image
        run: |
          docker pull --platform linux/amd64 ${{ matrix.registry }}:${{ github.sha }}-debian-amd64
          docker pull --platform linux/arm64 ${{ matrix.registry }}:${{ github.sha }}-debian-arm64
          docker buildx imagetools create \
            --tag ${{ matrix.registry }}:latest-debian \
            ${{ matrix.registry }}:${{ needs.autotag.outputs.name }}-debian \
            ${{ matrix.registry }}:${{github.sha}}-debian-amd64 \
            ${{ matrix.registry }}:${{github.sha}}-debian-arm64


  github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs:
      - hackage-release
      - docker-release
      - build-linux
      - build-macos
      - build-windows
      - autotag
    if: needs.autotag.outputs.created
    permissions:
      id-token: write
      attestations: write
      artifact-metadata: write
    steps:

      - name: Download Linux x86
        uses: actions/download-artifact@v8
        with:
          name: hadolint-linux-amd64
          path: artifacts/hadolint-linux-x86_64

      - name: Download Linux arm64
        uses: actions/download-artifact@v8
        with:
          name: hadolint-linux-arm64
          path: artifacts/hadolint-linux-arm64

      - name: Download Macos x86
        uses: actions/download-artifact@v8
        with:
          name: hadolint-macos-x86_64
          path: artifacts/hadolint-macos-x86_64

      - name: Download Macos arm
        uses: actions/download-artifact@v8
        with:
          name: hadolint-macos-arm64
          path: artifacts/hadolint-macos-arm64

      - name: Download Windows x86
        uses: actions/download-artifact@v8
        with:
          name: hadolint-windows-x86_64
          path: artifacts/hadolint-windows-x86_64

      - name: Rename and Checksum
        run: |
          mv artifacts/hadolint-linux-x86_64/hadolint hadolint-linux-x86_64
          mv artifacts/hadolint-linux-arm64/hadolint hadolint-linux-arm64
          mv artifacts/hadolint-macos-x86_64/hadolint hadolint-macos-x86_64
          mv artifacts/hadolint-macos-arm64/hadolint hadolint-macos-arm64
          mv artifacts/hadolint-windows-x86_64/hadolint.exe hadolint-windows-x86_64.exe

          sha256sum -b hadolint* > checksums.sha256

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          draft: true
          files: |
            hadolint-linux-x86_64
            hadolint-linux-arm64
            hadolint-macos-x86_64
            hadolint-macos-arm64
            hadolint-windows-x86_64.exe
            checksums.sha256

      - name: Generate artifact attestations
        uses: actions/attest@v4
        with:
          subject-checksums: checksums.sha256
